export enum ErrorCode {
  // Connection Errors
  CONNECTION_FAILED = 'CONNECTION_FAILED',
  NOT_CONNECTED = 'NOT_CONNECTED',
  RELAY_CONNECTION_FAILED = 'RELAY_CONNECTION_FAILED',
  CONNECTION_TIMEOUT = 'CONNECTION_TIMEOUT',
  CONNECTION_LIMIT_EXCEEDED = 'CONNECTION_LIMIT_EXCEEDED',
  RELAY_TIMEOUT = 'RELAY_TIMEOUT',
  MAX_CONNECTIONS_EXCEEDED = 'MAX_CONNECTIONS_EXCEEDED',

  // Configuration Errors
  INVALID_CONFIG = 'INVALID_CONFIG',
  MISSING_CONFIG = 'MISSING_CONFIG',
  INVALID_KEY = 'INVALID_KEY',

  // Event Errors
  EVENT_VALIDATION_FAILED = 'EVENT_VALIDATION_FAILED',
  PUBLISH_FAILED = 'PUBLISH_FAILED',
  SUBSCRIPTION_FAILED = 'SUBSCRIPTION_FAILED',
  INVALID_EVENT = 'INVALID_EVENT',

  // Message Queue Errors
  INVALID_MESSAGE_TYPE = 'INVALID_MESSAGE_TYPE',
  QUEUE_FULL = 'QUEUE_FULL',

  // Security Errors
  ENCRYPTION_FAILED = 'ENCRYPTION_FAILED',
  DECRYPTION_FAILED = 'DECRYPTION_FAILED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  INVALID_SIGNATURE = 'INVALID_SIGNATURE',

  // Commerce Errors
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  INVOICE_CREATION_FAILED = 'INVOICE_CREATION_FAILED',
  INVOICE_NOT_FOUND = 'INVOICE_NOT_FOUND',
  PAYMENT_VERIFICATION_FAILED = 'PAYMENT_VERIFICATION_FAILED',
  INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',

  // Resource Errors
  NOT_FOUND = 'NOT_FOUND',
  ALREADY_EXISTS = 'ALREADY_EXISTS',
  RESOURCE_UNAVAILABLE = 'RESOURCE_UNAVAILABLE',

  // System Errors
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE'
}